DELETE FROM project_worker;
DELETE FROM project;
DELETE FROM worker;
DELETE FROM client;

ALTER TABLE worker ALTER COLUMN id RESTART WITH 1;
ALTER TABLE client ALTER COLUMN id RESTART WITH 1;
ALTER TABLE project ALTER COLUMN id RESTART WITH 1;